### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by principis** [NorfairKing/all-you-can-carry#11]
Misschien handing om een release toe te voegen met de gecompilede pdf's? Bij mij misten veel packages en zelfs dan werkte het nog niet (clean en pdf optie voor svg werkten niet) waarop ik heel texlive heb geïnstalleerd wat nogal een tijdverspilling is.

**Comment by NorfairKing** [comment]
Als je een release hebt kunnen compileren, dan accepteer ik graag een PR maar ik kan het me niet veroorloven om hier nog tijd in te steken.
Ik heb dit vijf jaar geleden gemaakt. Ik wist zelfs niet dat het nog gebruikt wordt.

**Comment by principis** [comment]
Geen probleem, ik kan zelf geen release maken, ook niet via een PR maar hier zijn alle gecompilede
 pdf's. (clean en pdf bij svg is nog steeds niet gelukt maar ik denk dat dat zelfs niet nodig. Ik weet zelf ook niet heel goed of het nog veel gebruikt wordt, maar het staat nog steeds op de wiki dus mogelijk wel. :)

[all-you-can-carry.pdf](https://github.com/NorfairKing/all-you-can-carry/files/3236639/all-you-can-carry.pdf)
[conditie_en_stabiliteit.pdf](https://github.com/NorfairKing/all-you-can-carry/files/3236640/conditie_en_stabiliteit.pdf)
[examenvragen.pdf](https://github.com/NorfairKing/all-you-can-carry/files/3236641/examenvragen.pdf)
[extra.pdf](https://github.com/NorfairKing/all-you-can-carry/files/3236642/extra.pdf)
[foutenanalyse.pdf](https://github.com/NorfairKing/all-you-can-carry/files/3236643/foutenanalyse.pdf)
[oefenzittingen.pdf](https://github.com/NorfairKing/all-you-can-carry/files/3236644/oefenzittingen.pdf)
[samenvatting.pdf](https://github.com/NorfairKing/all-you-can-carry/files/3236646/samenvatting.pdf)
[oud.pdf](https://github.com/NorfairKing/all-you-can-carry/files/3236647/oud.pdf)

Of als een zip gemakkelijker is voor jou.
[all-you-can-carry.zip](https://github.com/NorfairKing/all-you-can-carry/files/3236652/all-you-can-carry.zip)

**Comment by NorfairKing** [comment]
:+1: Thanks :D

**Comment by principis** [comment]
Oei, ik zag juist dat H08 en H09 niet in de samenvatting zit omdat die in samenvatting.tex niet stonden, geen idee waarom. Hier is in ieder geval een nieuwe versie. (Ik ben zelf aan het studeren dus heb de tijd niet om alles goed na te kijken.)

[all-you-can-carry.pdf](https://github.com/NorfairKing/all-you-can-carry/files/3240314/all-you-can-carry.pdf)
[samenvatting.pdf](https://github.com/NorfairKing/all-you-can-carry/files/3240308/samenvatting.pdf)
