### ISSUE TITLE
Mogelijke fouten.

### ISSUE THREAD

**Issue by TheOddler** [NorfairKing/all-you-can-carry#5]
Directe Methodes p2: Er wordt beschreven dat Xk zeer groot wordt, dus 1/Xk zeer klein. Dan staat er: dit geeft 1 + 1/(Xk=1). De "Xk=1" staat dus volledig onder de breukstreep. Moet dit niet (1 + 1/Xk) = 1 zijn? (haakjes voor de duidelijkheid).

Directe Methodes p10: onderaan, p(x) = 5 + ... moet p(x) = 0 + ... zijn denk ik. Waarschijnlijk is finale uitkomst van a3 dan ook fout.

Examen vragen 2012, vraag 1 Programma verschil, p4: onderaan staat "hierdoor zal bijvoorbeeld intern 10 \* 0.1 =/= .1" dit moet natuurlijk "10 \* 0.1 =/= 1" zijn, merk de weggelaten . op.

Examen vragen 2012, vraag 4 nulpunten met jacobi, p 11: ]-2, -oneindig[ is geen deel. Dan is 1 < abs(alpha). Deze verwarring kwam er volgens mij door dat in het boek staat dat "een element op de diagonaal...", maar het moet gelden voor alle elementen op de diagonaal volgens Wikipedia.
Welke wel er tot behoord: alpha in ]-2,-1[. Dit als je de rijen van het stelsel om draait, wat mag, want dat veranderd je stelsel niet. Het zorgt er mogelijk wel voor dat je nu de stijlste functie gebruikt als eerste, wat nodig is voor convergentie.

Examen vragen 2012, vraag 7 veeltermen met zo laag mogelijke graad, p15:
1) Het gegeven moet daar zijn: p(-1)=p(0)=p(1)
2) De "3de vergelijking" (die voor P(0)) staat gegeven als a0+a1+a2-a3=c. Dit moeten allemaal +'n zijn, dus: a0+a1+a2+a3=c. Verdere bij de uitwerking staat een tweede keer die - die daar niet hoort (in het stelsel). Als laatste staat er net boven de finale uitkomst a3=1, dit moet a3=-1 zijn. De finale uitkomst (c+x-x^3) is wel correct. (Je ziet daar ook dat a3=-1)

**Comment by NorfairKing** [comment]
Eerlijk gezegd is dit zo lang geleden dat ik het zelf niet meer weet.
Feel free to submit a pull request and I will merge it.

**Comment by TheOddler** [comment]
Zal hier foutjes die ik vindt bij zetten. Zal dan aanpassen als ik fatsoenlijk tijd heb er voor.

**Comment by TheOddler** [comment]
Syd, kan jij eens kijken naar die laatste die ik toegevoegd heb? Namelijk deze:

Examen vragen 2012, vraag 7 veeltermen met zo laag mogelijke graad, p15: De "3de vergelijking" (die voor P(0)) staat gegeven als a0+a1+a2-a3=c. Dit moeten allemaal +'n zijn, dus: a0+a1+a2+a3=c. Verdere uitrekening klopt dan ook niet meer.

Klopt het wat ik daar zet? :P

**Comment by NorfairKing** [comment]
Waat zet je dat? Waar heb je wat toegevoegd?

**Comment by NorfairKing** [comment]
Honestly, dit is voor mij al meer dan een jaar geleden. Ik heb er geen flauw idee meer van!

**Comment by TheOddler** [comment]
Dat is maar een fout die ik gevonden heb. Bij de examen vragen van 2012, de 7de vraag "veeltermen met zo laag mogelijke graad". Ergens verschijnt daar plots een minteken, terwijl dat volgens mij een + moet zijn. Dus ik denk dat het gewoon een foutje is.

Als je idd geen goesting hebt om dat uit te zoeken, zal ik het wel gewoon narekenen (was daar sowieso toch al mee bezig) dan zullen we zien of het juist is :P Maar al 3 keer achterlijke rekenfouten gemaakt, dus da gaat traag xD

**Comment by NorfairKing** [comment]
Allright. Ik geloof erin dat je dat correct doet, dus ik kijk uit naar uw pull-requests

**Comment by TheOddler** [comment]
Sgoed :P Die komen normaal na het examen, nu geen goesting om in de source code te gaan zoeken, vandaar dat ik hier de fouten oplijst die ik vind.

**Comment by NorfairKing** [comment]
Sguud. 1 request per fout graag.

**Comment by TheOddler** [comment]
ANARCHY!

**Comment by JeffHoremans** [comment]
@TheOddler Directe Methodes p10: onderaan, p(x) = 5 + ... moet p(x) = 0 + ... zijn denk ik. Waarschijnlijk is finale uitkomst van a3 dan ook fout. 
Nee toch? De fout is net dat p(0) = 0 bij de opgave, p(0) = 5 moet zijn. Want anders is p[0,1] = 4 ook fout. p onderaan is volgens mee dus wel correct.
