### ISSUE TITLE
Fout vraag 1 handgeschreven nota's Marc van Barel

### ISSUE THREAD

**Issue by TheOddler** [NorfairKing/all-you-can-carry#6]
Onderaan de handgeschreven oplossingen van vraag 1, staat er net boven het vierkantje met "alpha=3/2" de invulling van de berekening met effectieve waarden. Deze klopt niet, er zijn enkele -'n die +'n moeten zijn, en visa-versa.

De toteindelijke verkrgen waarde is wel juist. Heb dit nagerekend vanuit de formule waar de waardes nog niet ingevuld zijn.

**Comment by NorfairKing** [comment]
De handgeschreven oplossingen heb ik niet eens gemaakt :p

**Comment by TheOddler** [comment]
Dat maakt ze niet minder fout hé!
Is gwn, dan pas ik dat aan na het examen. Of ik heb mij toch voorgenomen dat te doen, omdat ze mij wel goed geholpen hebben al.

**Comment by NorfairKing** [comment]
Super! Dankje :D
