### ISSUE TITLE
Deel 1 vraag 5: foutje in matrix (p. 8)

### ISSUE THREAD

**Issue by JeffHoremans** [NorfairKing/all-you-can-carry#9]
Het bekomen stelsel in het antwoord, de 3de rij moet [1 1 1 1] zijn ipv [1 1 1 -1]. 
p(1) zorgt er namelijk voor dat alle coëfficiënten gewoon worden opgeteld.
De oplossing van het stelsel is wel juist, dus ik vermoed dat dit gewoon een typfout is geweest.

**Comment by NorfairKing** [comment]
Dankje! Pull request?

**Comment by JeffHoremans** [comment]
Blijkbaar had Pablo dit ook al aangehaald in zijn issue (met al zijn gevonden fouten in). Dat had ik pas achteraf gezien, maar dit is overzichtelijker denk ik. Hij was al van plan om na de examens pull requests te maken, dus wss zal hij deze wel mee verhelpen. Ik heb nu weinig tijd (net als hem morgen examen), maar in het andere geval zal ik het binnenkort verhelpen.
